# Generated by Django 4.2.20 on 2025-03-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '職種', 'verbose_name_plural': '職種'},
        ),
        migrations.AlterModelOptions(
            name='shifttype',
            options={'verbose_name': 'シフトの種類', 'verbose_name_plural': 'シフトの種類'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'スタッフ情報', 'verbose_name_plural': 'スタッフ情報'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['date', 'shift'], 'verbose_name': '勤務シフト', 'verbose_name_plural': '勤務シフト'},
        ),
    ]
