# Generated by Django 4.2.20 on 2025-04-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_shifttype_break_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='full_name',
            new_name='name',
        ),
    ]
