# Generated by Django 4.2.20 on 2025-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_rename_full_name_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='meal_note',
            field=models.TextField(blank=True, null=True, verbose_name='食事に関する備考'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='needs_breakfast',
            field=models.BooleanField(default=False, verbose_name='朝食要るか'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='needs_dinner',
            field=models.BooleanField(default=False, verbose_name='夕食要るか'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='needs_lunch',
            field=models.BooleanField(default=False, verbose_name='昼食要るか'),
        ),
    ]
