# Generated by Django 4.2.20 on 2025-03-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittype',
            name='arrive_time',
            field=models.TimeField(null=True, verbose_name='来所時間'),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='leave_time',
            field=models.TimeField(null=True, verbose_name='帰宅時間'),
        ),
    ]
