# Generated by Django 4.2.20 on 2025-03-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_visittype_arrive_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': '利用者情報', 'verbose_name_plural': '利用者情報'},
        ),
        migrations.AlterModelOptions(
            name='visitschedule',
            options={'ordering': ['date'], 'verbose_name': '来訪スケジュール', 'verbose_name_plural': '来訪スケジュール'},
        ),
        migrations.AlterModelOptions(
            name='visittype',
            options={'verbose_name': '来訪種別', 'verbose_name_plural': '来訪種別'},
        ),
    ]
