# Generated by Django 4.2.20 on 2025-04-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_guest_options_alter_visitschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visittype',
            name='arrive_time',
        ),
        migrations.RemoveField(
            model_name='visittype',
            name='leave_time',
        ),
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='arrive_time',
            field=models.TimeField(null=True, verbose_name='来所時間'),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='leave_time',
            field=models.TimeField(null=True, verbose_name='帰宅時間'),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='来訪種別'),
        ),
    ]
