# Generated by Django 4.2.20 on 2025-04-16 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_remove_visittype_arrive_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='full_name',
            new_name='name',
        ),
    ]
