# Generated by Django 4.2.20 on 2025-04-18 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0005_rename_full_name_guest_name'),
        ('staff', '0005_rename_full_name_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='コード')),
                ('display_name', models.CharField(max_length=20, verbose_name='表示名')),
            ],
            options={
                'verbose_name': '食事の種類',
                'verbose_name_plural': '食事の種類',
            },
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('ordered', models.BooleanField(default=True, verbose_name='注文あり')),
                ('auto_generated', models.BooleanField(default=True, verbose_name='自動生成')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.guest', verbose_name='患者')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.mealtype', verbose_name='食事の種類')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '食事の注文',
                'verbose_name_plural': '食事の注文',
                'unique_together': {('date', 'meal_type', 'guest', 'staff')},
            },
        ),
    ]
