# Generated by Django 4.2.20 on 2025-03-25 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='スタッフ'),
        ),
        migrations.AlterUniqueTogether(
            name='mealorder',
            unique_together={('date', 'meal_type', 'guest', 'staff')},
        ),
    ]
