# Generated by Django 4.2.20 on 2025-03-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealorder',
            options={'verbose_name': '食事の注文', 'verbose_name_plural': '食事の注文'},
        ),
        migrations.AlterModelOptions(
            name='mealtype',
            options={'verbose_name': '食事の種類', 'verbose_name_plural': '食事の種類'},
        ),
    ]
